[project]
name = "lsd-mcp"
version = "0.1.1"
description = "Connect Claude to the internet with LSD SQL"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.2.1",
    "psycopg2-binary>=2.9.10",
]
